# Backdrop recipe
name: serundeputy

# Start with the default Backdrop recipe
recipe: backdrop

# Configure the Backdrop recipe
config:
  via: nginx
  php: '7.3'
  webroot: www
  backdrush: 1.x-1.x
  database: mariadb:10.2
  xdebug: true

env_file:
  - .env

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install
      - composer global require laravel/envoy

# See: https://docs.lndo.io/config/tooling.html
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://serundeputy.lndo.site
  envoy:
    service: appserver
  pull:
    service: appserver
    description: Pull and import the database from production.
    cmd:
      - appserver: envoy run pull
      - database: /helpers/sql-import.sh db.sql
      - appserver: rm db.sql
      - appserver: rm -rf /app/www/files
      - appserver: tar xvzf f.tgz -C /app/www
      - appserver: rm f.tgz
  deploy:
    service: appserver
    description: Deploy to production
    cmd:
      - appserver: envoy run deploy --branch=master
