# Backdrop recipe
name: serundeputy

# Start with the default Backdrop recipe
recipe: backdrop

# Configure the Backdrop recipe
config:
  via: nginx
  php: '7.0'
  webroot: www
  backdrush: dev
  database: mariadb:10.2
  xdebug: true

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install
      - composer global require laravel/envoy
  node-cli:
    type: node:10
    ports:
      - 3000:3000
      - 3001:3001
    globals:
      gulp-cli: "latest"

# See: https://docs.lndo.io/config/tooling.html
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://serundeputy.lndo.site
  envoy:
    service: appserver
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli

