# Backdrop recipe
name: serundeputy

# Start with the default Backdrop recipe
recipe: backdrop

# Configure the Backdrop recipe
config:
  via: nginx
  php: '7.3'
  webroot: www
  backdrush: 1.0.0
  database: mariadb:10.2
  xdebug: true

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install
      - composer global require laravel/envoy

# See: https://docs.lndo.io/config/tooling.html
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://serundeputy.lndo.site
  envoy:
    service: appserver

