services:

  # What to call the service hosting the site.
  php:

    # Use the latest PHP 7.x with Apache
    image: tugboatqa/php:7-apache
    default: true

    # Wait until the mysql service is done building
    depends: mysql

    # A set of commands to run while building this service
    commands:

      # The `init` commands sets up the basic preview infrastructure
      init:
        - a2enmod headers rewrite
        - docker-php-ext-install opcache

        # Install Drush 8.x
        - composer --no-ansi global require drush/drush:8.x
        - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush

        # Install Backdrop-specific Drush commands
        - mkdir -p ~/.drush/commands/
        - cd ~/.drush/commands/ && wget https://github.com/backdrop-contrib/drush/archive/1.x-0.x.zip
        - cd ~/.drush/commands/ && unzip 1.x-0.x.zip -d backdrop

        # Link the serundrop webroot
        - ln -sf "${TUGBOAT_ROOT}/www" "${DOCROOT}"
        - cp -av "${TUGBOAT_ROOT}/config/staging ${TUGBOAT_ROOT}/config/active"

        # Use the tugboat-specific Backdrop settings
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php"
          "${TUGBOAT_ROOT}/www/settings.php"

        # Setup the necessary file permissions.
        - mkdir -p "${DOCROOT}/files"
        - chown www-data "${DOCROOT}/files"
        - chmod 744 "${DOCROOT}/files"

      # Commands that build the site. When a preview is built from a
      # base preview, the build workflow starts here, skipping the init
      # and update steps, because the results of those are inherited
      # from the base preview.
      build:
        - drush -r "${DOCROOT}/www" cache-clear all
        - drush -r "${DOCROOT}/www" updatedb -y

  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:

    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mysql:5
    # A set of commands to run while building this service
    commands:
      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      update:
        # Copy a database dump from an external server. The public
        # SSH key found in the Tugboat Repository configuration must be
        # copied to the external server in order to use scp.
        - scp gff@serundeputy.io:/home/gff/backups/serundeputy/tugboat/database.sql.gz /tmp/database.sql.gz
        - zcat /tmp/database.sql.gz | mysql tugboat
        - rm /tmp/database.sql.gz
