<?php
require_once BACKDROP_ROOT . "/../vendor/autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

/**
 * Implements hook_block_info().
 */
function serundeputy_tweets_block_info() {
  $blocks['serundeputy_tweets_block'] = array(
    'info' => t('Serundeputy Tweets'),
    'description' => t('Get tweets from twitter API.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @see _serundeputy_tweets_get_tweets().
 */
function serundeputy_tweets_block_view($delta = '', $settings = array()) {
  $block = array();

  // Block content.
  $content = _serundeputy_tweets_get_tweets();

  switch ($delta) {
    case 'serundeputy_tweets_block':
      $block['subject'] = NULL;
      $block['content'] = $content;
      return $block;
  }
}

/**
 * Get tweets.
 */
function _serundeputy_tweets_get_tweets() {
  global $settings;

  $consumer_key = $settings['consumer_key'];
  $consumer_secret = $settings['consumer_secret'];
  $access_token = $settings['access_token'];
  $access_token_secret = $settings['access_token_secret'];

  $connection = new TwitterOAuth($consumer_key, $consumer_secret, $access_token, $access_token_secret);
  $statuses = $connection->get(
    "search/tweets", ["q" => "#backdropintheevening", "count" => 4]
  );

  // Build up the markup from the API Request.
  $x = [];
  $markup = "<div class='container serundeputy-tweets-container'>";
    $markup .= "<div class='row serundeputy-tweets-row'>";
      foreach ($statuses as $status) {
        foreach ($status as $s) {
          $x[] = $s;
          if ($s->text) {
            $markup .= "<div class='serundeputy-tweet col-md-3'>$s->text</div>";
          }
        }
      }
    $markup .= "</div>";
  $markup .= "</div>";

  return $markup;
}
